import 'dart:io';
import 'dart:isolate';

import 'package:build/build.dart';
import 'package:build_test/build_test.dart';
import 'package:continuum_generator/builder.dart';
import 'package:package_config/package_config.dart';
import 'package:test/test.dart';

void main() {
  late final PackageConfig packageConfig;
  late TestReaderWriter readerWriter;

  setUpAll(() async {
    // In some CI environments (notably when running tests via workspace tooling),
    // `Isolate.packageConfig` can be null. Fall back to locating the
    // `.dart_tool/package_config.json` file relative to the working directory.
    Uri? packageConfigUri = await Isolate.packageConfig;
    packageConfigUri ??= _tryFindPackageConfigUriFromWorkingDirectory();

    if (packageConfigUri == null) {
      throw StateError(
        'Missing package config. `Isolate.packageConfig` was null and no '
        '`.dart_tool/package_config.json` could be found from `${Directory.current.path}`.',
      );
    }

    packageConfig = await loadPackageConfigUri(packageConfigUri);
  });

  setUp(() async {
    readerWriter = TestReaderWriter(rootPackage: 'continuum_generator');
    await readerWriter.testing.loadIsolateSources();
  });

  group('CombiningBuilder', () {
    test('generates lib/continuum.g.dart for aggregate roots', () async {
      // Arrange: Provide a synthetic `$lib$` input and a single annotated
      // aggregate. This verifies the happy path where at least one aggregate
      // exists and a combining output should be produced.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      // Act + Assert: The output should exist and contain expected imports and
      // the aggregate registration entry.
      await testBuilder(
        builder,
        {
          'continuum_generator|lib/user.dart': """
import 'package:bounded/bounded.dart';

final class UserId extends TypedIdentity<String> {
  const UserId(super.value);
}

class User extends AggregateRoot<UserId> {
  User(super.id);
}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            allOf(
              contains("import 'package:continuum/continuum.dart';"),
              contains("import 'user.dart';"),
              contains(r'final List<GeneratedAggregate> $targetList = ['),
              contains(r'  $User,'),
              contains(r"@Deprecated('Use $targetList instead.')"),
              contains(r'final List<GeneratedAggregate> $aggregateList = $targetList;'),
            ),
          ),
        },
      );
    });

    test('skips Freezed-like part files and still generates output', () async {
      // Arrange: A common real-world case is a generated `*.freezed.dart` file
      // under `lib/` that is a `part of` file (not a standalone library).
      // The builder must skip it to avoid `Asset ... is not a Dart library`.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      // Act + Assert: Build succeeds and output is generated.
      await testBuilder(
        builder,
        {
          'continuum_generator|lib/user.dart': """
import 'package:bounded/bounded.dart';

final class UserId extends TypedIdentity<String> {
  const UserId(super.value);
}

class User extends AggregateRoot<UserId> {
  User(super.id);
}
""",
          'continuum_generator|lib/repository_error.dart': """
part 'repository_error.freezed.dart';

class RepositoryError {}
""",
          'continuum_generator|lib/repository_error.freezed.dart': """
part of 'repository_error.dart';

// Intentionally minimal. In real apps this file is generated by Freezed.
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            allOf(
              contains("import 'user.dart';"),
              contains(r'  $User,'),
            ),
          ),
        },
      );
    });

    test('skips non-library part files even without generated suffix', () async {
      // Arrange: Not all part files end with known generated suffixes.
      // This validates the `resolver.isLibrary(...)` guard.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      // Act + Assert: Build succeeds and output is generated.
      await testBuilder(
        builder,
        {
          'continuum_generator|lib/user.dart': """
import 'package:bounded/bounded.dart';

final class UserId extends TypedIdentity<String> {
  const UserId(super.value);
}

class User extends AggregateRoot<UserId> {
  User(super.id);
}
""",
          'continuum_generator|lib/odd_library.dart': """
part 'odd_part.dart';

class OddLibrary {}
""",
          'continuum_generator|lib/odd_part.dart': """
part of 'odd_library.dart';

class OddPart {}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            contains(r'  $User,'),
          ),
        },
      );
    });

    test('does not generate output when no aggregates exist', () async {
      // Arrange: If no aggregate roots exist, emitting an empty
      // `continuum.g.dart` would be surprising for users.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      // Act + Assert: No outputs should be written.
      await testBuilder(
        builder,
        {
          'continuum_generator|lib/not_an_aggregate.dart': '''
class NotAnAggregate {}
''',
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: const {},
      );
    });

    test('generates registerAll extension for single-stream inline projection', () async {
      // Arrange: A single-stream inline projection should produce a registerAll
      // extension with the correct parameter types (StreamId key) and call
      // registerGeneratedInline.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      await testBuilder(
        builder,
        {
          'continuum_generator|lib/user_profile_projection.dart': """
import 'package:continuum/src/annotations/projection.dart';
import 'package:continuum/src/projections/single_stream_projection.dart';
import 'package:continuum/src/events/continuum_event.dart';

class UserRegistered implements ContinuumEvent {
  const UserRegistered();
  @override String get id => 'id';
  @override DateTime get occurredOn => DateTime(1970);
  @override Map<String, Object?> get metadata => const {};
}

@Projection(name: 'user-profile', events: [UserRegistered])
class UserProfileProjection extends SingleStreamProjection<int> {
  @override
  int createInitial(streamId) => 0;

  @override
  int apply(int current, operation) => current;
}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            allOf(
              // Verify $projectionList is emitted.
              contains(r'$UserProfileProjection,'),
              // Verify registerAll extension is emitted.
              contains(r'extension $ProjectionRegistryExtensions on ProjectionRegistry'),
              contains('void registerAll('),
              // Verify parameter names are correct.
              contains('required UserProfileProjection userProfileProjection'),
              // Verify store type uses StreamId for single-stream.
              contains('required ReadModelStore<int, StreamId> userProfileStore'),
              // Verify inline lifecycle registration.
              contains('registerGeneratedInline('),
              // Verify the bundle variable is passed.
              contains(r'$UserProfileProjection,'),
            ),
          ),
        },
      );
    });

    test('generates \$createInlineProjectionHandler for inline projections', () async {
      // Arrange: An inline projection should produce a $createInlineProjectionHandler
      // function that returns CommitHandler and internally creates registry + executor + handler.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      await testBuilder(
        builder,
        {
          'continuum_generator|lib/user_profile_projection.dart': """
import 'package:continuum/src/annotations/projection.dart';
import 'package:continuum/src/projections/single_stream_projection.dart';
import 'package:continuum/src/events/continuum_event.dart';

class UserRegistered implements ContinuumEvent {
  const UserRegistered();
  @override String get id => 'id';
  @override DateTime get occurredOn => DateTime(1970);
  @override Map<String, Object?> get metadata => const {};
}

@Projection(name: 'user-profile', events: [UserRegistered])
class UserProfileProjection extends SingleStreamProjection<int> {
  @override
  int createInitial(streamId) => 0;

  @override
  int apply(int current, operation) => current;
}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            allOf(
              // Verify the continuum_uow import is present.
              contains("import 'package:continuum_uow/continuum_uow.dart';"),
              // Verify the function signature.
              contains(r'CommitHandler $createInlineProjectionHandler('),
              contains('required UserProfileProjection userProfileProjection'),
              contains('required ReadModelStore<int, StreamId> userProfileStore'),
              // Verify internal wiring.
              contains('final registry = ProjectionRegistry()'),
              contains('registry.registerGeneratedInline('),
              contains('return ProjectionCommitHandler(InlineProjectionExecutor(registry: registry))'),
            ),
          ),
        },
      );
    });

    test('does not generate \$createInlineProjectionHandler for async-only projections', () async {
      // Arrange: When all projections are async, no inline handler function should be emitted.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      await testBuilder(
        builder,
        {
          'continuum_generator|lib/async_projection.dart': """
import 'package:continuum/src/annotations/projection.dart';
import 'package:continuum/src/projections/single_stream_projection.dart';
import 'package:continuum/src/projections/projection_lifecycle.dart';
import 'package:continuum/src/events/continuum_event.dart';

class OrderPlaced implements ContinuumEvent {
  const OrderPlaced();
  @override String get id => 'id';
  @override DateTime get occurredOn => DateTime(1970);
  @override Map<String, Object?> get metadata => const {};
}

@Projection(name: 'order-summary', events: [OrderPlaced], lifecycle: ProjectionLifecycle.async)
class OrderSummaryProjection extends SingleStreamProjection<int> {
  @override
  int createInitial(streamId) => 0;

  @override
  int apply(int current, operation) => current;
}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            isNot(contains(r'$createInlineProjectionHandler')),
          ),
        },
      );
    });

    test('generates registerAll with registerGeneratedAsync for async projection', () async {
      // Arrange: An async projection should call registerGeneratedAsync.
      final builder = continuumCombiningBuilder(const BuilderOptions({}));

      await testBuilder(
        builder,
        {
          'continuum_generator|lib/async_projection.dart': """
import 'package:continuum/src/annotations/projection.dart';
import 'package:continuum/src/projections/single_stream_projection.dart';
import 'package:continuum/src/projections/projection_lifecycle.dart';
import 'package:continuum/src/events/continuum_event.dart';

class OrderPlaced implements ContinuumEvent {
  const OrderPlaced();
  @override String get id => 'id';
  @override DateTime get occurredOn => DateTime(1970);
  @override Map<String, Object?> get metadata => const {};
}

@Projection(name: 'order-summary', events: [OrderPlaced], lifecycle: ProjectionLifecycle.async)
class OrderSummaryProjection extends SingleStreamProjection<int> {
  @override
  int createInitial(streamId) => 0;

  @override
  int apply(int current, operation) => current;
}
""",
        },
        rootPackage: 'continuum_generator',
        packageConfig: packageConfig,
        readerWriter: readerWriter,
        outputs: {
          'continuum_generator|lib/continuum.g.dart': decodedMatches(
            allOf(
              contains('required OrderSummaryProjection orderSummaryProjection'),
              contains('required ReadModelStore<int, StreamId> orderSummaryStore'),
              contains('registerGeneratedAsync('),
            ),
          ),
        },
      );
    });
  });
}

/// Attempts to locate the workspace `.dart_tool/package_config.json` file.
///
/// CI and workspace runners can launch `dart test` in ways where
/// `Isolate.packageConfig` is unavailable. In those cases, build_test still
/// needs a real package config to resolve `package:` imports.
Uri? _tryFindPackageConfigUriFromWorkingDirectory() {
  Directory currentDirectory = Directory.current;
  while (true) {
    final Uri candidateUri = currentDirectory.uri.resolve('.dart_tool/package_config.json');
    if (File.fromUri(candidateUri).existsSync()) {
      return candidateUri;
    }

    final Directory parentDirectory = currentDirectory.parent;
    if (parentDirectory.path == currentDirectory.path) {
      return null;
    }

    currentDirectory = parentDirectory;
  }
}
