import '../operations/operation.dart';

/// Base class for all projection types.
///
/// Projections transform operations into read models. Each projection
/// specifies which event types it handles, how to extract a key from
/// an operation, how to create an initial read model, and how to apply
/// an operation to update the read model.
///
/// The [apply] method is typically generated by the code generator
/// via a mixin that dispatches to typed handler methods. The
/// [extractKey] and [createInitial] methods are implemented by the
/// user.
abstract class ProjectionBase<TReadModel, TKey> {
  /// The event types this projection handles.
  Set<Type> get handledEventTypes;

  /// The unique name for this projection.
  String get projectionName;

  /// Extracts the key for the read model from an operation.
  ///
  /// The implementation inspects the concrete operation type to
  /// determine which read model instance is affected.
  TKey extractKey(Operation operation);

  /// Creates an initial read model for the given key.
  TReadModel createInitial(TKey key);

  /// Applies an operation to an existing read model, returning the updated model.
  TReadModel apply(TReadModel current, Operation operation);

  /// Whether this projection handles events of the given [eventType].
  bool handles(Type eventType) => handledEventTypes.contains(eventType);
}
