name: continuum_example
description: Example demonstrating the Continuum event sourcing library.
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  continuum:
    path: ../
  continuum_event_sourcing:
    path: ../../continuum_event_sourcing
  continuum_state:
    path: ../../continuum_state
  continuum_store_memory:
    path: ../../continuum_store_memory
  continuum_uow:
    path: ../../continuum_uow

  bounded: ^2.0.0
  zooper_flutter_core: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^3.0.0
  continuum_generator:
    path: ../../continuum_generator

dependency_overrides:
  continuum:
    path: ../
  continuum_event_sourcing:
    path: ../../continuum_event_sourcing
  continuum_state:
    path: ../../continuum_state
  continuum_uow:
    path: ../../continuum_uow
