import 'package:continuum/continuum.dart';

/// Example creation event used by the missing-creation-factories lint.
///
/// This event is explicitly marked as a creation event, which means the
/// aggregate must define a matching `createFromAudioFileCreated(...)` factory.
@AggregateEvent(of: AudioFile, creation: true)
abstract class AudioFileCreated implements ContinuumEvent {
  /// Creates a test event instance.
  const AudioFileCreated();
}

/// Example event type used by the lint demonstration.
///
/// This event intentionally has no generator annotations because the lint rule
/// only cares about `apply<Event>(...)` handlers declared by the generated
/// `_$<Aggregate>EventHandlers` mixin.
sealed class AudioFileDeletedEvent implements ContinuumEvent {
  /// Creates a test event instance.
  const AudioFileDeletedEvent();
}

/// Mimics the mixin that would normally be generated by `continuum_generator`.
///
/// The lint rule derives required handlers from the abstract methods declared
/// on this mixin.
mixin _$AudioFileEventHandlers {
  /// Applies an [AudioFileDeletedEvent] to the aggregate.
  void applyAudioFileDeletedEvent(AudioFileDeletedEvent event);
}

/// Demonstrates both lint rules:
///
/// - `continuum_missing_apply_handlers`: this class is concrete, mixes in the
///   generated event handlers mixin, but does not implement
///   `applyAudioFileDeletedEvent(...)`.
/// - `continuum_missing_creation_factories`: the [AudioFileCreated] event is
///   marked as a creation event but the aggregate does not define
///   `createFromAudioFileCreated(...)`.
@Aggregate()
// ignore: continuum_missing_apply_handlers, continuum_missing_creation_factories
class AudioFile with _$AudioFileEventHandlers {
  /// Creates an [AudioFile].
  const AudioFile();

  /// Implements `noSuchMethod` so the class can remain concrete even though it
  /// does not implement all interface members.
  @override
  dynamic noSuchMethod(Invocation invocation) {
    return super.noSuchMethod(invocation);
  }
}
