import 'package:continuum/continuum.dart';

/// Example event type used by the lint demonstration.
sealed class AudioFileDeletedEvent implements ContinuumEvent {
  /// Creates a test event instance.
  const AudioFileDeletedEvent();
}

/// Mimics the mixin that would normally be generated by `continuum_generator`.
mixin _$AudioFileEventHandlers {
  /// Applies an [AudioFileDeletedEvent] to the aggregate.
  void applyAudioFileDeletedEvent(AudioFileDeletedEvent event);
}

/// Demonstrates the fixed variant: all required apply methods are implemented.
@Aggregate()
class AudioFile with _$AudioFileEventHandlers {
  /// Creates an [AudioFile].
  const AudioFile();

  @override
  void applyAudioFileDeletedEvent(AudioFileDeletedEvent event) {
    // Intentionally empty for example purposes.
  }
}
