import 'package:bounded/bounded.dart';
import 'package:continuum/continuum.dart';

/// A strongly-typed identifier for an audio file aggregate.
final class AudioFileId extends TypedIdentity<String> {
  /// Creates an audio file identifier from a stable string value.
  const AudioFileId(super.value);
}

/// Example event type used by the lint demonstration.
final class AudioFileDeletedEvent implements ContinuumEvent {
  /// Creates an [AudioFileDeletedEvent].
  AudioFileDeletedEvent({EventId? eventId, DateTime? occurredOn, Map<String, Object?> metadata = const <String, Object?>{}})
    : id = eventId ?? EventId.fromUlid(),
      occurredOn = occurredOn ?? DateTime.now(),
      metadata = Map<String, Object?>.unmodifiable(metadata);

  @override
  final EventId id;

  @override
  final DateTime occurredOn;

  @override
  final Map<String, Object?> metadata;
}

/// Mimics the mixin that would normally be generated by `continuum_generator`.
mixin _$AudioFileEventHandlers {
  /// Applies an [AudioFileDeletedEvent] to the aggregate.
  void applyAudioFileDeletedEvent(AudioFileDeletedEvent event);
}

/// Demonstrates the fixed variant: all required apply methods are implemented.
class AudioFile extends AggregateRoot<AudioFileId> with _$AudioFileEventHandlers {
  /// Creates an [AudioFile].
  AudioFile(super.id);

  @override
  void applyAudioFileDeletedEvent(AudioFileDeletedEvent event) {
    // Intentionally empty for example purposes.
  }
}
