// Mocks generated by Mockito 5.4.6 from annotations
// in continuum/test/persistence/session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:continuum/src/identity/stream_id.dart' as _i5;
import 'package:continuum/src/persistence/atomic_event_store.dart' as _i7;
import 'package:continuum/src/persistence/event_store.dart' as _i2;
import 'package:continuum/src/persistence/expected_version.dart' as _i6;
import 'package:continuum/src/persistence/stored_event.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i2.EventStore {
  @override
  _i3.Future<List<_i4.StoredEvent>> loadStreamAsync(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#loadStreamAsync, [streamId]),
            returnValue: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
          )
          as _i3.Future<List<_i4.StoredEvent>>);

  @override
  _i3.Future<void> appendEventsAsync(
    _i5.StreamId? streamId,
    _i6.ExpectedVersion? expectedVersion,
    List<_i4.StoredEvent>? events,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appendEventsAsync, [
              streamId,
              expectedVersion,
              events,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AtomicEventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicEventStore extends _i1.Mock implements _i7.AtomicEventStore {
  @override
  _i3.Future<void> appendEventsToStreamsAsync(
    Map<_i5.StreamId, _i7.StreamAppendBatch>? batches,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appendEventsToStreamsAsync, [batches]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.StoredEvent>> loadStreamAsync(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#loadStreamAsync, [streamId]),
            returnValue: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
          )
          as _i3.Future<List<_i4.StoredEvent>>);

  @override
  _i3.Future<void> appendEventsAsync(
    _i5.StreamId? streamId,
    _i6.ExpectedVersion? expectedVersion,
    List<_i4.StoredEvent>? events,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appendEventsAsync, [
              streamId,
              expectedVersion,
              events,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
