// Mocks generated by Mockito 5.4.6 from annotations
// in continuum/test/persistence/transactional_runner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:continuum/src/events/continuum_event.dart' as _i7;
import 'package:continuum/src/identity/stream_id.dart' as _i5;
import 'package:continuum/src/persistence/commit_handler.dart' as _i8;
import 'package:continuum/src/persistence/continuum_store.dart' as _i4;
import 'package:continuum/src/persistence/session.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContinuumSession_0 extends _i1.SmartFake
    implements _i2.ContinuumSession {
  _FakeContinuumSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T> extends _i1.SmartFake implements _i3.Future<T> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContinuumStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockContinuumStore extends _i1.Mock implements _i4.ContinuumStore {
  @override
  _i2.ContinuumSession openSession() =>
      (super.noSuchMethod(
            Invocation.method(#openSession, []),
            returnValue: _FakeContinuumSession_0(
              this,
              Invocation.method(#openSession, []),
            ),
            returnValueForMissingStub: _FakeContinuumSession_0(
              this,
              Invocation.method(#openSession, []),
            ),
          )
          as _i2.ContinuumSession);
}

/// A class which mocks [ContinuumSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockContinuumSession extends _i1.Mock implements _i2.ContinuumSession {
  @override
  _i3.Future<TAggregate> loadAsync<TAggregate>(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#loadAsync, [streamId]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<TAggregate>(
                    this,
                    Invocation.method(#loadAsync, [streamId]),
                  ),
                  (TAggregate v) => _i3.Future<TAggregate>.value(v),
                ) ??
                _FakeFuture_1<TAggregate>(
                  this,
                  Invocation.method(#loadAsync, [streamId]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<TAggregate>(
                    this,
                    Invocation.method(#loadAsync, [streamId]),
                  ),
                  (TAggregate v) => _i3.Future<TAggregate>.value(v),
                ) ??
                _FakeFuture_1<TAggregate>(
                  this,
                  Invocation.method(#loadAsync, [streamId]),
                ),
          )
          as _i3.Future<TAggregate>);

  @override
  _i3.Future<TAggregate> applyAsync<TAggregate>(
    _i5.StreamId? streamId,
    _i7.ContinuumEvent? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyAsync, [streamId, event]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<TAggregate>(
                    this,
                    Invocation.method(#applyAsync, [streamId, event]),
                  ),
                  (TAggregate v) => _i3.Future<TAggregate>.value(v),
                ) ??
                _FakeFuture_1<TAggregate>(
                  this,
                  Invocation.method(#applyAsync, [streamId, event]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<TAggregate>(
                    this,
                    Invocation.method(#applyAsync, [streamId, event]),
                  ),
                  (TAggregate v) => _i3.Future<TAggregate>.value(v),
                ) ??
                _FakeFuture_1<TAggregate>(
                  this,
                  Invocation.method(#applyAsync, [streamId, event]),
                ),
          )
          as _i3.Future<TAggregate>);

  @override
  _i3.Future<List<TAggregate>> loadAllAsync<TAggregate>() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllAsync, []),
            returnValue: _i3.Future<List<TAggregate>>.value(<TAggregate>[]),
            returnValueForMissingStub: _i3.Future<List<TAggregate>>.value(
              <TAggregate>[],
            ),
          )
          as _i3.Future<List<TAggregate>>);

  @override
  _i3.Future<List<_i7.ContinuumEvent>> saveChangesAsync({
    int? maxRetries = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveChangesAsync, [], {#maxRetries: maxRetries}),
            returnValue: _i3.Future<List<_i7.ContinuumEvent>>.value(
              <_i7.ContinuumEvent>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i7.ContinuumEvent>>.value(
                  <_i7.ContinuumEvent>[],
                ),
          )
          as _i3.Future<List<_i7.ContinuumEvent>>);

  @override
  void discardStream(_i5.StreamId? streamId) => super.noSuchMethod(
    Invocation.method(#discardStream, [streamId]),
    returnValueForMissingStub: null,
  );

  @override
  void discardAll() => super.noSuchMethod(
    Invocation.method(#discardAll, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CommitHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommitHandler extends _i1.Mock implements _i8.CommitHandler {
  @override
  _i3.Future<void> onCommitAsync(List<_i7.ContinuumEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#onCommitAsync, [events]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
