// Mocks generated by Mockito 5.4.6 from annotations
// in continuum_state/test/persistence/state_based_session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:continuum/continuum.dart' as _i5;
import 'package:continuum_state/src/persistence/target_persistence_adapter.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

import '../_fixtures/counter_fixtures.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TargetPersistenceAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockTargetPersistenceAdapter extends _i1.Mock
    implements _i2.TargetPersistenceAdapter<_i3.Counter> {
  @override
  _i4.Future<_i3.Counter> fetchAsync(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAsync, [streamId]),
            returnValue: _i4.Future<_i3.Counter>.value(
              _i6.dummyValue<_i3.Counter>(
                this,
                Invocation.method(#fetchAsync, [streamId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Counter>.value(
              _i6.dummyValue<_i3.Counter>(
                this,
                Invocation.method(#fetchAsync, [streamId]),
              ),
            ),
          )
          as _i4.Future<_i3.Counter>);

  @override
  _i4.Future<void> persistAsync(
    _i5.StreamId? streamId,
    _i3.Counter? target,
    List<_i5.Operation>? pendingOperations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#persistAsync, [
              streamId,
              target,
              pendingOperations,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAsync(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAsync, [streamId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
