// Mocks generated by Mockito 5.4.6 from annotations
// in continuum_event_sourcing/test/persistence/event_application_mode_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:continuum/continuum.dart' as _i5;
import 'package:continuum_event_sourcing/src/persistence/event_store.dart'
    as _i2;
import 'package:continuum_event_sourcing/src/persistence/expected_version.dart'
    as _i6;
import 'package:continuum_event_sourcing/src/persistence/stored_event.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i2.EventStore {
  @override
  _i3.Future<List<_i4.StoredEvent>> loadStreamAsync(_i5.StreamId? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#loadStreamAsync, [streamId]),
            returnValue: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.StoredEvent>>.value(
              <_i4.StoredEvent>[],
            ),
          )
          as _i3.Future<List<_i4.StoredEvent>>);

  @override
  _i3.Future<void> appendEventsAsync(
    _i5.StreamId? streamId,
    _i6.ExpectedVersion? expectedVersion,
    List<_i4.StoredEvent>? events, {
    required String? aggregateType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #appendEventsAsync,
              [streamId, expectedVersion, events],
              {#aggregateType: aggregateType},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.StreamId>> getStreamIdsByAggregateTypeAsync(
    String? aggregateType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStreamIdsByAggregateTypeAsync, [
              aggregateType,
            ]),
            returnValue: _i3.Future<List<_i5.StreamId>>.value(<_i5.StreamId>[]),
            returnValueForMissingStub: _i3.Future<List<_i5.StreamId>>.value(
              <_i5.StreamId>[],
            ),
          )
          as _i3.Future<List<_i5.StreamId>>);
}
